feat: Implementando o cadastro de usuário
devsis2022/gac-api pull request #2
Opened 2022-11-16 22:48 UTC by FelipeSchultzDev

- Configuração do inversify pra inversão de dependencia

2022-11-16 23:13 UTC, henrfarias requested changes

2022-11-16 23:13 UTC, henrfarias commented on prisma/schema.prisma
> -  username         String?            @unique @db.VarChar(30)
Remove não...

2022-11-16 23:13 UTC, henrfarias commented on src/config/application.ts
> +    this.express.use(json())
Aqui já acho legal adicionar a lib do cors também

2022-11-18 23:34 UTC, FelipeSchultzDev commented on prisma/schema.prisma
> -  username         String?            @unique @db.VarChar(30)
Arrumei, fei

2022-11-18 23:35 UTC, henrfarias approved these changes
🤠

2022-11-18 23:35 UTC, merged